version: 2.1
jobs:
  build:
    docker:
      - image: cimg/node:14.10.1 # the primary container, where your job's commands are run
    steps:
      - checkout # check out the code in the project directory
      - run: echo "installing npm packages" # run the `echo` command
      - run: npm install
      - run: CI=true npm run build
  test_back:
    docker:
      - image: cimg/node:14.10.1 # the primary container, where your job's commands are run
    steps:
      - checkout # check out the code in the project directory
      - run: echo "running backend tests" # run the `echo` command
      - run: npm install
      - run: npm run test:back
  test_front:
    docker:
      - image: cimg/node:14.10.1 # the primary container, where your job's commands are run
    steps:
      - checkout # check out the code in the project directory
      - run: echo "running backend tests" # run the `echo` command
      - run: npm install
      - run: npm run test:front
workflows:
  version: 2
  test_and_build:
    jobs:
      - test_back
      - test_front
      - build:
          requires:
            - test_back
            - test_front
